[workspace]
resolver = "2"
members = [
    "crates/utils",
    "crates/cli"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
tokio = {version = "1.53.1", features = ["full"]}
anyhow = "1.0.104"
uuid = {version = "1.24.0", features = ["v4"] }
# Shared dependencies across crates
