[package]
name = "flanix-core"
version.workspace = true
edition.workspace = true

[dependencies]
flanix-errors = { path = "../flanix-errors" }
flanix-config = { path = "../flanix-config" }
flanix-indexing = { path = "../flanix-indexing" }
chrono.workspace = true
tokio.workspace = true
uuid.workspace = true
thiserror.workspace = true
aws-sdk-s3.workspace = true
sqlx.workspace = true
aws-config = "1.10.1"

[dev-dependencies]
tempfile = "3.27.0"
anyhow.workspace = true

[lib]
path = "src/lib.rs"
