[package]
name = "Flanix"
version.workspace = true
edition.workspace = true
license = "MIT"
readme = "README.md"
repository = "https://github.com/dhogenson/sync"
authors = ["Dallin Hogenson <dallin.hogenson@icloud.com"]
description = "A syncing program"

[dependencies]
flanix-core = { path = "../flanix-core" }
tokio.workspace = true
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
