[package]
name = "flanix-errors"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
aws-sdk-s3.workspace = true
sqlx.workspace = true
glob.workspace = true
serde_json.workspace = true
toml.workspace = true
anyhow.workspace = true


[lib]
name = "sync_errors"
path = "src/lib.rs"
