[package]
name = "sync-core"
version.workspace = true
edition.workspace = true

[dependencies]
aws-config = { version = "1.10.1" }
aws-sdk-s3 = {version = "1.141.0" }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "uuid", "migrate", "chrono"] }
chrono = {version = "0.4.45", features = ["serde"]}
tokio.workspace = true
uuid.workspace = true
glob = "0.3.4"
thiserror = "2.0.20"
directories = "6.0.0"
serde = "1.0.229"
serde_json = "1.0.151"
dotenvy = "0.15.7"

[dev-dependencies]
tempfile = "3.27.0"
anyhow.workspace = true

[lib]
name = "sync_core"
path = "src/lib.rs"
