[package]
name = "sync-core"
version.workspace = true
edition.workspace = true

[dependencies]

sync-config = { path = "../sync-config" }
aws-config = { version = "1.10.1" }
# aws-sdk-s3 = {version = "1.141.0" }

chrono = {version = "0.4.45", features = ["serde"]}
tokio.workspace = true
uuid.workspace = true
glob = "0.3.4"
thiserror.workspace = true

serde.workspace = true
serde_json.workspace = true

aws-sdk-s3.workspace = true
sqlx.workspace = true
sync-errors = { path = "../sync-errors" }

[dev-dependencies]
tempfile = "3.27.0"
anyhow.workspace = true

[lib]
name = "sync_core"
path = "src/lib.rs"
