[package]
name = "sync-core"
version.workspace = true
edition.workspace = true

[dependencies]
sync-errors = { path = "../sync-errors" }
sync-config = { path = "../sync-config" }
sync-indexing = { path = "../sync-indexing" }
chrono.workspace = true
tokio.workspace = true
uuid.workspace = true
thiserror.workspace = true
aws-sdk-s3.workspace = true
sqlx.workspace = true
aws-config = "1.10.1"

[dev-dependencies]
tempfile = "3.27.0"
anyhow.workspace = true

[lib]
name = "sync_core"
path = "src/lib.rs"
